//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace UsePowerService.PowerService {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="PowerUsage_AllStations_OneSecond", Namespace="http://schemas.datacontract.org/2004/07/AdminPowerStations.APIs")]
    [System.SerializableAttribute()]
    public partial class PowerUsage_AllStations_OneSecond : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ErrorMessageField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private byte ReadingHourField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private byte ReadingMinuteField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private byte ReadingSecondField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private decimal Station01PowerUsageField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private decimal Station02PowerUsageField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private decimal Station03PowerUsageField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private decimal Station04PowerUsageField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private decimal Station05PowerUsageField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private decimal Station06PowerUsageField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private decimal Station07PowerUsageField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private decimal Station08PowerUsageField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private decimal Station09PowerUsageField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private decimal Station10PowerUsageField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ErrorMessage {
            get {
                return this.ErrorMessageField;
            }
            set {
                if ((object.ReferenceEquals(this.ErrorMessageField, value) != true)) {
                    this.ErrorMessageField = value;
                    this.RaisePropertyChanged("ErrorMessage");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public byte ReadingHour {
            get {
                return this.ReadingHourField;
            }
            set {
                if ((this.ReadingHourField.Equals(value) != true)) {
                    this.ReadingHourField = value;
                    this.RaisePropertyChanged("ReadingHour");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public byte ReadingMinute {
            get {
                return this.ReadingMinuteField;
            }
            set {
                if ((this.ReadingMinuteField.Equals(value) != true)) {
                    this.ReadingMinuteField = value;
                    this.RaisePropertyChanged("ReadingMinute");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public byte ReadingSecond {
            get {
                return this.ReadingSecondField;
            }
            set {
                if ((this.ReadingSecondField.Equals(value) != true)) {
                    this.ReadingSecondField = value;
                    this.RaisePropertyChanged("ReadingSecond");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public decimal Station01PowerUsage {
            get {
                return this.Station01PowerUsageField;
            }
            set {
                if ((this.Station01PowerUsageField.Equals(value) != true)) {
                    this.Station01PowerUsageField = value;
                    this.RaisePropertyChanged("Station01PowerUsage");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public decimal Station02PowerUsage {
            get {
                return this.Station02PowerUsageField;
            }
            set {
                if ((this.Station02PowerUsageField.Equals(value) != true)) {
                    this.Station02PowerUsageField = value;
                    this.RaisePropertyChanged("Station02PowerUsage");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public decimal Station03PowerUsage {
            get {
                return this.Station03PowerUsageField;
            }
            set {
                if ((this.Station03PowerUsageField.Equals(value) != true)) {
                    this.Station03PowerUsageField = value;
                    this.RaisePropertyChanged("Station03PowerUsage");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public decimal Station04PowerUsage {
            get {
                return this.Station04PowerUsageField;
            }
            set {
                if ((this.Station04PowerUsageField.Equals(value) != true)) {
                    this.Station04PowerUsageField = value;
                    this.RaisePropertyChanged("Station04PowerUsage");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public decimal Station05PowerUsage {
            get {
                return this.Station05PowerUsageField;
            }
            set {
                if ((this.Station05PowerUsageField.Equals(value) != true)) {
                    this.Station05PowerUsageField = value;
                    this.RaisePropertyChanged("Station05PowerUsage");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public decimal Station06PowerUsage {
            get {
                return this.Station06PowerUsageField;
            }
            set {
                if ((this.Station06PowerUsageField.Equals(value) != true)) {
                    this.Station06PowerUsageField = value;
                    this.RaisePropertyChanged("Station06PowerUsage");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public decimal Station07PowerUsage {
            get {
                return this.Station07PowerUsageField;
            }
            set {
                if ((this.Station07PowerUsageField.Equals(value) != true)) {
                    this.Station07PowerUsageField = value;
                    this.RaisePropertyChanged("Station07PowerUsage");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public decimal Station08PowerUsage {
            get {
                return this.Station08PowerUsageField;
            }
            set {
                if ((this.Station08PowerUsageField.Equals(value) != true)) {
                    this.Station08PowerUsageField = value;
                    this.RaisePropertyChanged("Station08PowerUsage");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public decimal Station09PowerUsage {
            get {
                return this.Station09PowerUsageField;
            }
            set {
                if ((this.Station09PowerUsageField.Equals(value) != true)) {
                    this.Station09PowerUsageField = value;
                    this.RaisePropertyChanged("Station09PowerUsage");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public decimal Station10PowerUsage {
            get {
                return this.Station10PowerUsageField;
            }
            set {
                if ((this.Station10PowerUsageField.Equals(value) != true)) {
                    this.Station10PowerUsageField = value;
                    this.RaisePropertyChanged("Station10PowerUsage");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="PowerUsage_OneStation_15Minutes", Namespace="http://schemas.datacontract.org/2004/07/AdminPowerStations.APIs")]
    [System.SerializableAttribute()]
    public partial class PowerUsage_OneStation_15Minutes : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ErrorMessageField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private decimal[] PowerUsageField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private byte ReadingHourField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private byte StartReadingMinuteField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string StationLocationField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string StationNameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private byte StationNumberField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string StationPhoneField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ErrorMessage {
            get {
                return this.ErrorMessageField;
            }
            set {
                if ((object.ReferenceEquals(this.ErrorMessageField, value) != true)) {
                    this.ErrorMessageField = value;
                    this.RaisePropertyChanged("ErrorMessage");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public decimal[] PowerUsage {
            get {
                return this.PowerUsageField;
            }
            set {
                if ((object.ReferenceEquals(this.PowerUsageField, value) != true)) {
                    this.PowerUsageField = value;
                    this.RaisePropertyChanged("PowerUsage");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public byte ReadingHour {
            get {
                return this.ReadingHourField;
            }
            set {
                if ((this.ReadingHourField.Equals(value) != true)) {
                    this.ReadingHourField = value;
                    this.RaisePropertyChanged("ReadingHour");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public byte StartReadingMinute {
            get {
                return this.StartReadingMinuteField;
            }
            set {
                if ((this.StartReadingMinuteField.Equals(value) != true)) {
                    this.StartReadingMinuteField = value;
                    this.RaisePropertyChanged("StartReadingMinute");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string StationLocation {
            get {
                return this.StationLocationField;
            }
            set {
                if ((object.ReferenceEquals(this.StationLocationField, value) != true)) {
                    this.StationLocationField = value;
                    this.RaisePropertyChanged("StationLocation");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string StationName {
            get {
                return this.StationNameField;
            }
            set {
                if ((object.ReferenceEquals(this.StationNameField, value) != true)) {
                    this.StationNameField = value;
                    this.RaisePropertyChanged("StationName");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public byte StationNumber {
            get {
                return this.StationNumberField;
            }
            set {
                if ((this.StationNumberField.Equals(value) != true)) {
                    this.StationNumberField = value;
                    this.RaisePropertyChanged("StationNumber");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string StationPhone {
            get {
                return this.StationPhoneField;
            }
            set {
                if ((object.ReferenceEquals(this.StationPhoneField, value) != true)) {
                    this.StationPhoneField = value;
                    this.RaisePropertyChanged("StationPhone");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="PowerService.IPowerService")]
    public interface IPowerService {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IPowerService/ReportStationsAll", ReplyAction="http://tempuri.org/IPowerService/ReportStationsAllResponse")]
        UsePowerService.PowerService.PowerUsage_AllStations_OneSecond ReportStationsAll(string hour, string minute, string second);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IPowerService/ReportStationsAll", ReplyAction="http://tempuri.org/IPowerService/ReportStationsAllResponse")]
        System.Threading.Tasks.Task<UsePowerService.PowerService.PowerUsage_AllStations_OneSecond> ReportStationsAllAsync(string hour, string minute, string second);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IPowerService/ReportOneStation", ReplyAction="http://tempuri.org/IPowerService/ReportOneStationResponse")]
        UsePowerService.PowerService.PowerUsage_OneStation_15Minutes ReportOneStation(string stationNumber, string hour, string minutes);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IPowerService/ReportOneStation", ReplyAction="http://tempuri.org/IPowerService/ReportOneStationResponse")]
        System.Threading.Tasks.Task<UsePowerService.PowerService.PowerUsage_OneStation_15Minutes> ReportOneStationAsync(string stationNumber, string hour, string minutes);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IPowerServiceChannel : UsePowerService.PowerService.IPowerService, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class PowerServiceClient : System.ServiceModel.ClientBase<UsePowerService.PowerService.IPowerService>, UsePowerService.PowerService.IPowerService {
        
        public PowerServiceClient() {
        }
        
        public PowerServiceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public PowerServiceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public PowerServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public PowerServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public UsePowerService.PowerService.PowerUsage_AllStations_OneSecond ReportStationsAll(string hour, string minute, string second) {
            return base.Channel.ReportStationsAll(hour, minute, second);
        }
        
        public System.Threading.Tasks.Task<UsePowerService.PowerService.PowerUsage_AllStations_OneSecond> ReportStationsAllAsync(string hour, string minute, string second) {
            return base.Channel.ReportStationsAllAsync(hour, minute, second);
        }
        
        public UsePowerService.PowerService.PowerUsage_OneStation_15Minutes ReportOneStation(string stationNumber, string hour, string minutes) {
            return base.Channel.ReportOneStation(stationNumber, hour, minutes);
        }
        
        public System.Threading.Tasks.Task<UsePowerService.PowerService.PowerUsage_OneStation_15Minutes> ReportOneStationAsync(string stationNumber, string hour, string minutes) {
            return base.Channel.ReportOneStationAsync(stationNumber, hour, minutes);
        }
    }
}
